name: Test Project
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 #External action from the marketplace
      - name: Install nodeJS
        uses: actions/setup-python@v4
        with: # Optional configuration. See docs at https://github.com/actions/setup-python.
          python-version: '3.10' 
      - name: Install dependencies
        run: pip install -r requirements.txt  
      - name: Run tests
        run: pytest
